name: azure-java-webapp

trigger:
  branches:
    include:
      - main

pool:
  name: Uday

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
