name: azure-java-webapp

trigger:
  branches:
    include:
      - main

pool:
  name: Ubuntu

stages:
  - stage: Build
    jobs:
    - job: Buildjob
      displayName: 'Build Job'
      steps:
      - script: |
          echo "Maven packaging process"
          mvn clean package
        displayName: 'Package with Maven'  
