name: azure-java-webapp



trigger:
  - main

pool:
  name: Ubuntu

stages:
  - stage: Build
    jobs:
    - job: Buildjob
      displayName: 'Build Job'
      steps:
      - script: |
          echo "Maven packaging process"
          mvn clean package
        displayName: 'Package with Maven'
      - task: CopyFiles@2
        inputs:
          targetFolder: '$(Build.ArtifactStagingDirectory)'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
          
      - task: DownloadBuildArtifacts@1
        inputs:
          buildType: 'current'
          downloadType: 'single'
          downloadPath: '$(System.ArtifactsDirectory)'   
      
      - task: Docker@2
        inputs:
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
      